"""Regenerate the checked-in menu bitmap using Noto Sans CJK SC (OFL 1.1)."""
import argparse
import hashlib
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--font', type=Path, required=True)
    args = parser.parse_args()
    font = ImageFont.truetype(str(args.font), 18)
    chars = sorted(set((ROOT/'src/platform/menu.c').read_text(encoding='utf-8')) | set(map(chr,range(32,127))))
    chars = [c for c in chars if ord(c)>=32 and c not in '\r\n']
    out = ['/* Noto Sans CJK SC rendered glyph subset; OFL 1.1.',
           ' * See assets/licenses/NotoSansCJK-OFL.txt and assets/README.md.',
           ' * Generated by tools/generate_menu_font.py. */',
           '#ifndef H1_MENU_FONT_H', '#define H1_MENU_FONT_H',
           'static const struct { uint32_t code, rows[20]; } menu_glyphs[] = {']
    for char in chars:
        bitmap = Image.new('L',(18,20))
        ImageDraw.Draw(bitmap).text((0,0),char,font=font,fill=255,anchor='lt')
        rows = [sum(1<<x for x in range(18) if bitmap.getpixel((x,y))>=96) for y in range(20)]
        out.append('{%d,{%s}},'%(ord(char),','.join('0x%x'%v for v in rows)))
    out += ['};','#define MENU_GLYPH_COUNT (sizeof menu_glyphs/sizeof menu_glyphs[0])','#endif']
    (ROOT/'src/platform/menu_font.h').write_text('\n'.join(out)+'\n',encoding='utf-8')
    print('glyphs',len(chars),'font SHA256',hashlib.sha256(args.font.read_bytes()).hexdigest())

if __name__ == '__main__': main()
